### ISSUE TITLE
Can I upload a TicTacToe Game made in python?

### ISSUE THREAD

**Issue by XCalibur5678** [SamarthTech/Hacktoberfest-Project-and-Games#4]
Here is the link to the repo https://github.com/XCalibur5678/Hacktoberfest-Project-and-Games

**Comment by codingniket** [comment]
Yes

**Comment by XCalibur5678** [comment]
> Yes

I have sent the pull request dada. Please go through it and let me know if any changes are required

**Comment by codingniket** [comment]
@XCalibur5678 Thanks for hacking with us!
