### ISSUE TITLE
Improving Index.html file

### ISSUE THREAD

**Issue by sudhanshugautam2911** [SamarthTech/Hacktoberfest-Project-and-Games#42]

**Comment by sudhanshugautam2911** [comment]
Can you please add label of hacktoberfest and assign me this issue? I am also in your team in Hacksquad

**Comment by sudhanshugautam2911** [comment]
Assign me this issue and add label of hacktoberfest then merge my pull request

**Comment by jaskirat0001** [comment]
Assign me this task
